[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[theme]
primaryColor = "#818cf8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9fafb"
textColor = "#09090b"
font = "sans serif"

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = true
enableWebsocketCompression = true




